export enum DOMContainerId {
  AppBody="app-body",
  Header="header",
  Logo = "logo",
  Search= "search",
  User = "user",
  Aside = "aside",
  AsideList = "aside-list",
  Tracks = "tracks",
  TracksCaption = "tracks_caption",
  TracksList = "tracks-list",
  Playlist = "playlist",
  PlaylistList = "playlist-list",
  PlaylistsModal = "playlists-modal",
  Player = "player",
  PlayerTrackInfo = "player-track-info",
  PlayerControls = "player-controls",
  PlayerPlayStopButton = "player-playstopbtn",
  PlayerProgress = "range-play",
  PlaylistsModalContent = "playlists-modal-content",
  TrackActionsModal = "track-actions-modal",
  AddPlaylistModal = "addplaylist-modal",
}